### ISSUE TITLE
Bus balance issue

### ISSUE THREAD

**Issue by cswh** [znes/openmod.sh#2]
When

* running d8a6047b346fa257a24ef1a3b6f5784f368df143,
* importing `data/scenarios/Variante 01 GMK1000 ohne Speicher.json` and
* clicking on `Run Simulation`,

the job reports as `failed` after a while with the following info:

```
Failure.
Traceback (most recent call last):
File "~/openmod.sh/openmod/sh/mcbeth.py", line 550, in wrapped_simulation es = create_model(es)
File "~/openmod.sh/openmod/sh/mcbeth.py", line 447, in create_model es.model = OperationalModel(es=es)
File "~/openmod.sh/dependencies/oemof/oemof/solph/models.py", line 202, in __init__ block._create(group=self.es.groups.get(group))
File "~/openmod.sh/dependencies/oemof/oemof/solph/blocks.py", line 781, in _create self.balance_build = BuildAction(rule=_busbalance_rule)
File "~/openmod.sh/venv/lib/python3.5/site-packages/pyomo/core/base/block.py", line 540, in __setattr__ self.add_component(name, val)
File "~/openmod.sh/venv/lib/python3.5/site-packages/pyomo/core/base/block.py", line 980, in add_component val.construct(data)
File "~/openmod.sh/venv/lib/python3.5/site-packages/pyomo/core/base/action.py", line 60, in construct self._rule(self._parent())
File "~/openmod.sh/dependencies/oemof/oemof/solph/blocks.py", line 779, in _busbalance_rule block.balance.add((n, t), expr)
File "~/openmod.sh/venv/lib/python3.5/site-packages/pyomo/core/base/constraint.py", line 1106, in add return self.__setitem__(index, expr)
File "~/openmod.sh/venv/lib/python3.5/site-packages/pyomo/core/base/indexed_component.py", line 586, in __setitem__ index = self._validate_index(index)
File "~/openmod.sh/venv/lib/python3.5/site-packages/pyomo/core/base/indexed_component.py", line 695, in _validate_index % ( idx, self.name, ))
KeyError: "Index '(, 0)' is not valid for indexed component 'Bus.balance'" 
```

@simnh  Can you have a look on that?

**Comment by simnh** [comment]
This was due to a new pyomo version. I fixed this now by setting the version to 5.3 in the requirements.txt. This solves the problem.
